export const SET_ORDER_NUMBER_OF_SWEETS = 'SET_ORDER_NUMBER_OF_SWEETS';
export const SET_ORDER_OUTPUT_SWEET_PACKS = 'SET_ORDER_OUTPUT_SWEET_PACKS';
export const SET_SHOW_ORDER_ERROR = 'SET_SHOW_ORDER_ERROR';
export const SET_ORDER_ERROR_MESSAGE = 'SET_ORDER_ERROR_MESSAGE';

export const ADD_SWEET_PACK_SIZE = 'ADD_SWEET_PACK_SIZE';
export const REMOVE_SWEET_PACK_SIZE = 'REMOVE_SWEET_PACK_SIZE';
export const UPDATE_SWEET_PACK_SIZE = 'UPDATE_SWEET_PACK_SIZE';
export const SET_SHOW_INVENTORY_ERROR = 'SET_SHOW_INVENTORY_ERROR';
export const SET_INVENTORY_ERROR_MESSAGE = 'SET_INVENTORY_ERROR_MESSAGE';
