export const SET_ORDER_NUMBER_OF_SWEETS = 'SET_ORDER_NUMBER_OF_SWEETS';

export const ADD_SWEET_PACK_SIZE = 'ADD_SWEET_PACK_SIZE';
export const REMOVE_SWEET_PACK_SIZE = 'REMOVE_SWEET_PACK_SIZE';
export const UPDATE_SWEET_PACK_SIZE = 'UPDATE_SWEET_PACK_SIZE';
